name: employee_attendance
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.3.3
  cupertino_icons: ^0.1.3

  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6
  
  jiffy: ^3.0.1
  table_calendar: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura.ttf
    - family: FuturaBold
      fonts:
        - asset: assets/fonts/FuturaBold.ttf